name: flutter_firebase_auth_template
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.1 <4.0.0"

dependencies:
  dartz: ^0.10.1
  flutter_easyloading: ^3.0.5
  equatable: ^2.0.5
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  get_it: ^7.6.7
  intl: ^0.19.0

dev_dependencies:
  build_runner: ^2.4.8
  firebase_auth_mocks: ^0.13.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mock_exceptions: ^0.8.2
  mockito: ^5.4.4

flutter:
  uses-material-design: true
